In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(
    r"D:\Vehicle_Mileage_Project\data\processed\cleaned_dataset.csv"
)

df.head()

,Vehicle_ID,Manufacturer,Model,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Fuel_Type,Ethanol_Blend,...,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,CO2_Emission_g_km,Fuel_Consumption_L_100km,Mileage_km_per_L
0,V014767,Tata,Nexon,13.0,1000.0,82.0,1307.0,Automatic,Petrol,20.0,...,High,27.0,61.0,Fog,No,Normal,1.0,192.1,5.00,20.02
1,V020736,Toyota,Glanza,8.0,1200.0,98.0,1493.0,Automatic,Petrol,20.0,...,High,30.0,48.0,Fog,Yes,Smooth,3.0,189.2,5.12,19.52
2,V041583,Maruti,Baleno,9.0,1200.0,103.0,1262.0,Automatic,Petrol,20.0,...,Medium,34.0,44.0,Fog,Yes,Aggressive,1.0,197.3,5.55,18.01
3,V042258,Honda,City,14.0,1200.0,95.0,1001.0,Manual,Petrol,10.0,...,High,15.0,53.0,Rain,Yes,Normal,1.0,185.8,5.23,19.12
4,V029600,Tata,Altroz,15.0,1800.0,148.0,1604.0,Manual,Petrol,10.0,...,Medium,24.0,65.0,Fog,Yes,Smooth,1.0,197.7,5.90,16.96

In [3]:
df.drop(
    columns=[
        "Vehicle_ID",
        "Manufacturer",
        "Model",
        "CO2_Emission_g_km",
        "Fuel_Consumption_L_100km"
    ],
    inplace=True
)

df.head()

,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Fuel_Type,Ethanol_Blend,Fuel_Price,Trip_Distance_km,Average_Speed,...,Maintenance_Status,Road_Type,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,Mileage_km_per_L
0,13.0,1000.0,82.0,1307.0,Automatic,Petrol,20.0,110.94,471.8,41.0,...,Average,Highway,High,27.0,61.0,Fog,No,Normal,1.0,20.02
1,8.0,1200.0,98.0,1493.0,Automatic,Petrol,20.0,98.96,494.3,54.0,...,Poor,Highway,High,30.0,48.0,Fog,Yes,Smooth,3.0,19.52
2,9.0,1200.0,103.0,1262.0,Automatic,Petrol,20.0,99.59,389.2,67.0,...,Good,Mixed,Medium,34.0,44.0,Fog,Yes,Aggressive,1.0,18.01
3,14.0,1200.0,95.0,1001.0,Manual,Petrol,10.0,109.11,563.2,65.0,...,Poor,Mixed,High,15.0,53.0,Rain,Yes,Normal,1.0,19.12
4,15.0,1800.0,148.0,1604.0,Manual,Petrol,10.0,111.82,417.0,73.0,...,Good,Mixed,Medium,24.0,65.0,Fog,Yes,Smooth,1.0,16.96

In [4]:
df.columns

Index(['Vehicle_Age', 'Engine_CC', 'Horsepower', 'Vehicle_Weight',
       'Transmission', 'Fuel_Type', 'Ethanol_Blend', 'Fuel_Price',
       'Trip_Distance_km', 'Average_Speed', 'Engine_RPM', 'Tire_Pressure_PSI',
       'Maintenance_Status', 'Road_Type', 'Traffic_Level', 'Temperature',
       'Humidity', 'Weather', 'AC_Usage', 'Driving_Style', 'Passengers',
       'Mileage_km_per_L'],
      dtype='str')

In [5]:
df["Fuel_Type"].value_counts()

Fuel_Type
Petrol    63973
Name: count, dtype: int64

In [6]:
df.drop(columns=["Fuel_Type"], inplace=True)

In [7]:
df.dtypes

Vehicle_Age           float64
Engine_CC             float64
Horsepower            float64
Vehicle_Weight        float64
Transmission              str
Ethanol_Blend         float64
Fuel_Price            float64
Trip_Distance_km      float64
Average_Speed         float64
Engine_RPM            float64
Tire_Pressure_PSI     float64
Maintenance_Status        str
Road_Type                 str
Traffic_Level             str
Temperature           float64
Humidity              float64
Weather                   str
AC_Usage                  str
Driving_Style             str
Passengers            float64
Mileage_km_per_L      float64
dtype: object

In [8]:
categorical_columns = df.select_dtypes(include=["object","string"]).columns

categorical_columns

Index(['Transmission', 'Maintenance_Status', 'Road_Type', 'Traffic_Level',
       'Weather', 'AC_Usage', 'Driving_Style'],
      dtype='str')

In [9]:
encoder = LabelEncoder()

for col in categorical_columns:
    df[col] = encoder.fit_transform(df[col])

In [10]:
df.head()

,Vehicle_Age,Engine_CC,Horsepower,Vehicle_Weight,Transmission,Ethanol_Blend,Fuel_Price,Trip_Distance_km,Average_Speed,Engine_RPM,...,Maintenance_Status,Road_Type,Traffic_Level,Temperature,Humidity,Weather,AC_Usage,Driving_Style,Passengers,Mileage_km_per_L
0,13.0,1000.0,82.0,1307.0,0,20.0,110.94,471.8,41.0,3668.0,...,0,1,0,27.0,61.0,1,0,1,1.0,20.02
1,8.0,1200.0,98.0,1493.0,0,20.0,98.96,494.3,54.0,1284.0,...,2,1,0,30.0,48.0,1,1,2,3.0,19.52
2,9.0,1200.0,103.0,1262.0,0,20.0,99.59,389.2,67.0,2469.0,...,1,2,2,34.0,44.0,1,1,0,1.0,18.01
3,14.0,1200.0,95.0,1001.0,1,10.0,109.11,563.2,65.0,3499.0,...,2,2,0,15.0,53.0,2,1,1,1.0,19.12
4,15.0,1800.0,148.0,1604.0,1,10.0,111.82,417.0,73.0,1755.0,...,1,2,2,24.0,65.0,1,1,2,1.0,16.96

In [11]:
df.dtypes

Vehicle_Age           float64
Engine_CC             float64
Horsepower            float64
Vehicle_Weight        float64
Transmission            int64
Ethanol_Blend         float64
Fuel_Price            float64
Trip_Distance_km      float64
Average_Speed         float64
Engine_RPM            float64
Tire_Pressure_PSI     float64
Maintenance_Status      int64
Road_Type               int64
Traffic_Level           int64
Temperature           float64
Humidity              float64
Weather                 int64
AC_Usage                int64
Driving_Style           int64
Passengers            float64
Mileage_km_per_L      float64
dtype: object

In [12]:
X = df.drop("Mileage_km_per_L", axis=1)

y = df["Mileage_km_per_L"]

In [13]:
print(X.shape)
print(y.shape)

(63973, 20)
(63973,)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [15]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(51178, 20)
(12795, 20)
(51178,)
(12795,)

In [17]:
from sklearn.ensemble import AdaBoostRegressor

ada_model = AdaBoostRegressor(
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

ada_model.fit(X_train, y_train)

ada_pred = ada_model.predict(X_test)

print("AdaBoost")
print("R2 Score :", r2_score(y_test, ada_pred))
print("MAE      :", mean_absolute_error(y_test, ada_pred))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, ada_pred)))

AdaBoost
R2 Score : 0.6614949091604154
MAE      : 1.6250753543174945
RMSE     : 2.031603161918719

In [20]:
from catboost import CatBoostRegressor

cat_model = CatBoostRegressor(
    iterations=500,
    learning_rate=0.1,
    depth=6,
    random_seed=42,
    verbose=0
)

cat_model.fit(X_train, y_train)

cat_pred = cat_model.predict(X_test)

print("CatBoost")
print("R2 Score :", r2_score(y_test, cat_pred))
print("MAE      :", mean_absolute_error(y_test, cat_pred))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, cat_pred)))

CatBoost
R2 Score : 0.9717473919475376
MAE      : 0.5062297808217986
RMSE     : 0.5869289752597856

In [19]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)

ridge_model.fit(X_train, y_train)

ridge_pred = ridge_model.predict(X_test)

print("Ridge Regression")
print("R2 Score :", r2_score(y_test, ridge_pred))
print("MAE      :", mean_absolute_error(y_test, ridge_pred))
print("RMSE     :", np.sqrt(mean_squared_error(y_test, ridge_pred)))

Ridge Regression
R2 Score : 0.7619801661629984
MAE      : 1.3930304753465763
RMSE     : 1.703581250701337

In [21]:
results = pd.DataFrame({
    "Model": [
        
        "AdaBoost",
        "CatBoost",
        "Ridge Regression"
    ],
    "R2 Score": [
        
        r2_score(y_test, ada_pred),
        r2_score(y_test, cat_pred),
        r2_score(y_test, ridge_pred)
    ],
    "MAE": [
        
        mean_absolute_error(y_test, ada_pred),
        mean_absolute_error(y_test, cat_pred),
        mean_absolute_error(y_test, ridge_pred)
    ],
    "RMSE": [
        
        np.sqrt(mean_squared_error(y_test, ada_pred)),
        np.sqrt(mean_squared_error(y_test, cat_pred)),
        np.sqrt(mean_squared_error(y_test, ridge_pred))
    ]
})

results.sort_values(by="R2 Score", ascending=False)

              Model  R2 Score       MAE      RMSE
1          CatBoost  0.971747  0.506230  0.586929
2  Ridge Regression  0.761980  1.393030  1.703581
0          AdaBoost  0.661495  1.625075  2.031603

In [22]:
import joblib

# Save AdaBoost
joblib.dump(
    ada_model,
    r"D:\Vehicle_Mileage_Project\models\adaboost.pkl"
)

# Save Ridge Regression
joblib.dump(
    ridge_model,
    r"D:\Vehicle_Mileage_Project\models\ridge_regression.pkl"
)

# Save CatBoost
joblib.dump(
    cat_model,
    r"D:\Vehicle_Mileage_Project\models\catboost.pkl"
)

['D:\\Vehicle_Mileage_Project\\models\\catboost.pkl']

In [23]:
joblib.dump(
    cat_model,
    r"D:\Vehicle_Mileage_Project\models\best_model.pkl"
)

print("Best model (CatBoost) saved successfully!")

Best model (CatBoost) saved successfully!

In [24]:
import os

print(os.listdir(r"D:\Vehicle_Mileage_Project\models"))

['adaboost.pkl', 'best_model.pkl', 'catboost.pkl', 'ridge_regression.pkl']

In [25]:
from catboost import CatBoostRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Base Model
cat_model = CatBoostRegressor(
    random_seed=42,
    verbose=0
)

# Parameters
param_grid = {
    "iterations": [300, 500],
    "depth": [4, 6, 8],
    "learning_rate": [0.01, 0.05, 0.1]
}

# Grid Search
grid_search = GridSearchCV(
    estimator=cat_model,
    param_grid=param_grid,
    scoring="r2",
    cv=5,
    n_jobs=-1,
    verbose=2
)

# Train
grid_search.fit(X_train, y_train)

# Best Model
best_grid_model = grid_search.best_estimator_

# Prediction
y_pred = best_grid_model.predict(X_test)

# Results
print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

print("\nTest Performance")
print("R2 :", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

Fitting 5 folds for each of 18 candidates, totalling 90 fits
Best Parameters: {'depth': 4, 'iterations': 500, 'learning_rate': 0.05}
Best CV Score: 0.9721037667057828

Test Performance
R2 : 0.9720935465218391
MAE: 0.504193556030801
RMSE: 0.5833223294324532

In [26]:
import joblib

joblib.dump(
    best_grid_model,
    r"D:\Vehicle_Mileage_Project\models\catboost_gridsearch.pkl"
)

['D:\\Vehicle_Mileage_Project\\models\\catboost_gridsearch.pkl']

In [27]:
from catboost import CatBoostRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# Base Model
cat_model = CatBoostRegressor(
    random_seed=42,
    verbose=0
)

# Parameters
param_dist = {
    "iterations": [300, 500, 700, 900],
    "depth": [4, 5, 6, 7, 8, 10],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "l2_leaf_reg": [1, 3, 5, 7, 9]
}

# Random Search
random_search = RandomizedSearchCV(
    estimator=cat_model,
    param_distributions=param_dist,
    n_iter=10,
    scoring="r2",
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

# Train
random_search.fit(X_train, y_train)

# Best Model
best_random_model = random_search.best_estimator_

# Prediction
y_pred = best_random_model.predict(X_test)

# Results
print("Best Parameters:", random_search.best_params_)
print("Best CV Score:", random_search.best_score_)

print("\nTest Performance")
print("R2 :", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Best Parameters: {'learning_rate': 0.03, 'l2_leaf_reg': 7, 'iterations': 900, 'depth': 4}
Best CV Score: 0.9721397519852804

Test Performance
R2 : 0.9720338046318364
MAE: 0.5044808677168657
RMSE: 0.5839463812743696

In [28]:
import joblib

joblib.dump(
    best_random_model,
    r"D:\Vehicle_Mileage_Project\models\catboost_randomsearch.pkl"
)

['D:\\Vehicle_Mileage_Project\\models\\catboost_randomsearch.pkl']

In [29]:
import joblib

joblib.dump(
    best_grid_model,
    r"D:\Vehicle_Mileage_Project\models\best_model.pkl"
)

print("GridSearchCV model saved as best_model.pkl")

GridSearchCV model saved as best_model.pkl